# Jekyll Resume Theme

# Site settings
title: Tinydew4 Resume
email: tinydew4@gmail.com
description: .
baseurl: "/resume"
url: "http://tinydew4.github.io"
name: Hur jung-ju
job: Windows application developer
location: Seoul, Korea
languages: C, C++, HTML, CSS and Javascript
# twitter_username: tinydew4
github_username:  tinydew4
gitlab_username:  tinydew4
email_address: tinydew4@gmail.com

# Build settings
markdown: kramdown
