# Jekyll Resume Theme

# Site settings
title: Tinydew4 Resume
email: tinydew4@gmail.com
description: .
baseurl: ""
url: "http://tinydew4.github.io/resume"
name: Hur jungju
job: Application Developer
location: Seoul, Korea
languages: C, C++, HTML, CSS and Javascript
twitter_username: 
github_username:  tinydew4
codepen_username:  tinydew4
email_address: tinydew4@gmail.com

# Build settings
markdown: kramdown
