# Jekyll Resume Theme

# Site settings
title:
  en: Hur jung ju - Resume
  ko: 허정주 - 이력서
email: tinydew4@gmail.com
description:
  en: resume
  ko: 이력서
baseurl: "/resume"
url: "http://tinydew4.github.io"
name:
  en: Hur jung-ju
  ko: 허정주
job:
  en: Windows application developer
  ko: 윈도우 응용프로그램 개발자
location:
  en: Seoul, Korea
  ko: 대한민국 서울
languages:
  en: C, C++, CSS and Javascript
  ko: C, C++, CSS, Javascript
# twitter_username: tinydew4
github_username: tinydew4
gitlab_username: tinydew4
email_address: tinydew4@gmail.com

# Build settings
markdown: kramdown
